version: '3.1'
services:
  portainer:
    image: portainer/portainer-ce:2.14.2-alpine
    container_name: portainer
    hostname: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    ports:
      - 9000:9000
    networks:
      - dev_mac

networks:
  dev_mac:
    name: dev_mac_bridge
    driver: bridge