version: '3.1'
services:
  namenode:
    image: packet23/hadoop-hdfs-namenode:3.3.3
    container_name: namenode
    hostname: namenode
    ports:
      - 9870:9870
    volumes:
      - ./conf:/hadoop/etc/hadoop
      - ./data/namenode:/data
    restart: always

  datanode01:
    image: packet23/hadoop-hdfs-datanode:3.3.3
    container_name: datanode01
    hostname: datanode01
    volumes:
      - ./conf:/hadoop/etc/hadoop
      - ./data/datanode01:/data
    restart: always
    depends_on:
      - namenode

  datanode02:
    image: packet23/hadoop-hdfs-datanode:3.3.3
    container_name: datanode02
    hostname: datanode02
    volumes:
      - ./conf:/hadoop/etc/hadoop
      - ./data/datanode02:/data
    restart: always
    depends_on:
      - namenode

  resourcemanager:
    image: packet23/hadoop-yarn-resourcemanager:3.3.3
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - 8088:8088
    volumes:
      - ./conf:/hadoop/etc/hadoop
    restart: always
    depends_on:
      - namenode

  nodemanager01:
    image: packet23/hadoop-yarn-nodemanager:3.3.3
    container_name: nodemanager01
    hostname: nodemanager01
    volumes:
      - ./conf:/hadoop/etc/hadoop
      - ./data/nodemanager01:/data
    restart: always
    depends_on:
      - namenode
      - datanode01
      - datanode02
      - resourcemanager

  nodemanager02:
    image: packet23/hadoop-yarn-nodemanager:3.3.3
    container_name: nodemanager02
    hostname: nodemanager02
    volumes:
      - ./conf:/hadoop/etc/hadoop
      - ./data/nodemanager02:/data
    restart: always
    depends_on:
      - namenode
      - datanode01
      - datanode02
      - resourcemanager

  jobhistoryserver:
    image: packet23/hadoop-mapred-jobhistoryserver:3.3.3
    ports:
      - 19888:19888
    volumes:
      - ./conf:/hadoop/etc/hadoop
    restart: always
    hostname: jobhistoryserver
    container_name: jobhistoryserver
    depends_on:
      - namenode
      - resourcemanager

networks:
  default:
    external: true
    name: dev_mac_bridge